config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :restaurants do
  	resources :reviews, except: [:show, :index]
  end
  get 'pages/about'

  get 'pages/contact'

  root 'restaurants#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :reviews

	validates :name, :address, :phone, :website, :image, presence: true
	#validates :phone, format: { with: /\A\(\d{3}\) \d{3}-\d{4}\z/,
	#	message: "must be in the format (123) 456-7890" }
	validates :website, format: { with: /\Ahttps?:\/\/.*\z/,
		message: "must start with http:// or https://" }
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :restaurant


	validates :rating, :comment, presence: true
	validates :rating, numericality: {
		only_integer: true,
		greater_than_or_equal_to: 1,
		less_than_or_equal_to: 5,
		message: "can only be a whole number between 1 and 5"
	}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :reviews, dependent: :destroy




  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name,:email,:password,:remember_me) }  
  
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name,:last_name, :email,:password,:current_password) }  
     
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, except: [:index, :show] 

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @reviews = Review.where(restaurant_id: @restaurant.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "Sorry, Admin only"
        
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone, :website, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_restaurant
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]
  # GET /reviews
  # GET /reviews.json
   
  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.restaurant_id = @restaurant.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to restaurant_path(@restaurant), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to root_path, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_path(@restaurant), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def check_user
      unless (@review.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Sorry, this review belongs to someone else"
        
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment, :restaurant_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright Chima Okochi</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">YelpDemo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="pages/about">About <span class="sr-only">(current)</span></a></li>
        <li><a href="pages/contact">Contact</a></li>
        
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
<% if user_signed_in? %>

 
      <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <li><a>Hi <%= current_user.first_name %></a> </li>


 

      <% else %>
      <li><%= link_to 'Login', new_user_session_path %></li>
      <li><%= link_to 'Signup', new_user_registration_path %></li>
     
<% end %>
   
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelpdemo</title>
    <%= csrf_meta_tags %>
<!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>

 <%= render 'layouts/header' %>
  	 <div class="container-fluid">

       <% flash.each do |name,msg| %>
       <h1><%= content_tag(:div, msg, class: "alert alert-info") %></h1>
       <% end %>

       <%= yield %>
       <%= render 'layouts/footer' %>
     </div>     
  </body>
</html>

app/views/pages/about.html.erb
 

<h1>Welcome To Film Critic!</h1>
<h2>This a film critic site built by <a href="http://www.chima66.herokuapp.com">Chima Okochi</a></h2>
<h2> He's awesome!</h2>
 

app/views/pages/contact.html.erb
<h1>We would love to hear from you!</h1>
<p>Contact us at wordhouse66@outlook.com</p>

app/views/restaurants/_form.html.erb
 <%= form_for(restaurant, :html => {multipart: true}) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
     <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h4>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Tony's Eatery" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control", placeholder: "13A National Street, Naija, Nigeria" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control", placeholder: "+234 80 1234 6789" %>
  </div>

  <div class="form-group">
    <%= f.label :website %>
    <%= f.text_field :website, class: "form-control", placeholder: "http://www.tonys.com" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant, class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
<h2>Yelpdemo is the best way to find reviews on local restaurants</h2>
<h3>Explore the favorite diners, pastry shops, and eateries in your community.<br>
    Leave reviews for your fellow foodies.</h3>
</div>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website %></td>

        <% if user_signed_in? && current_user.admin? %>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link"  %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link"  %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Restaurant', new_restaurant_path, class: "btn btn-link"  %>
<% end %>

<%= image_tag 'https://s3.amazonaws.com/yelpdemo66/uploads/happy_footer.png' %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path, class: "btn btn-link"  %>

app/views/restaurants/show.html.erb
<div class="row">
  <div class="col-md-3">
  	<%= image_tag @restaurant.image_url %>
<!--</div>-->
    <h2>
      
      <%= @restaurant.name %>
    </h2>

    <div class="star-rating" data-score=<%= @avg_rating %> ></div>
    <p><%= "#{@reviews.length} reviews " %></p>

    <p>
      <strong>Address:</strong>
      <%= @restaurant.address %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @restaurant.phone %>
    </p>

    <p>
       <strong>Website:</strong>
       <%= link_to @restaurant.website, @restaurant.website %>
    </p>

    <%= link_to 'Write a Review', new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
    <br><br>
    <iframe width="230" height="230"> src="//www.google.com/maps/embed/v1/place?q=<%= @restaurant.address.parameterize %>
      &zoom=17
      &key=AIzaSyAQEHQoysTxvNSp2K81TiAIao2NjGF_IE4">
    </iframe>
  </div>

  <div class="col-md-9">
  	<% if @reviews.blank? %>
  	   <h3>No reviews yet. Be the first to write one!</h3>
  	<% else %>
  	   <table class="table">
  	   	 <thead>
  	   	 	<tr>
  	   	 		<th class="col-md-3"></th>
  	   	 		<th class="col-md-9"></th>
  	   	 	</tr>
  	   	 </thead>
  	   	<tbody>
  	   	  <% @reviews.each do |review| %>
  	   	     <tr>
  	   	     	<td>
  	   	     	  <h4>
  	   	     	  	<%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
  	   	     	  </h4>
  	   	     	  <p><%= review.created_at.strftime("%-m/%-d/%y") %></p>
  	   	     	</td>
  	   	     	<td>
  	   	     	  <div class="star-rating" data-score=<%= review.rating %> ></div>
                  <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>

                  <% if user_signed_in? %>
                    <% if (review.user == current_user) || (current_user.admin?) %>
                      <%= link_to "Edit", edit_restaurant_review_path(@restaurant, review) %>
                      <%= link_to "Delete", restaurant_review_path(@restaurant, review), method: :delete %>
                    <% end %>
                  <% end %>
                </td>
             </tr>	
  	   	  <% end %>	
  	   	</tbody>
  	   </table>
  	   

  	<% end %>
  	
  </div>
</div><!--<div class="thumbnail" style="height: 400px; width: 400px;">-->




<%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

<script >
	$('.star-rating').raty({
		path: 'https://s3.amazonaws.com/yelpdemo66/stars',
		readOnly: true,
		score: function() {
          return $(this).attr('data-score');
        }
	});
</script>

app/views/reviews/_form.html.erb
<%= form_for([@restaurant, @review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="star-rating"></div>

  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script >
  $('#star-rating').raty({
    path: 'https://s3.amazonaws.com/yelpdemo66/stars',
     scoreName: 'review[rating]' 
     
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

 
<%= link_to 'Back', restaurant_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', restaurant_path(@restaurant) %>